"""empty message

Revision ID: 9312fe6dc2f1
Revises: d98b07afedca
Create Date: 2024-05-09 00:29:33.045306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9312fe6dc2f1'
down_revision = 'd98b07afedca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_code', sa.String(length=10), nullable=False))
        batch_op.drop_constraint('enrol_accessCode_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'administrator', ['access_code'], ['access_code'])
        batch_op.drop_column('accessCode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accessCode', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('enrol_accessCode_fkey', 'administrator', ['accessCode'], ['access_code'])
        batch_op.drop_column('access_code')

    # ### end Alembic commands ###
