"""empty message

Revision ID: d98b07afedca
Revises: 3ced50bb1cc7
Create Date: 2024-05-08 20:38:19.944265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98b07afedca'
down_revision = '3ced50bb1cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_camera_question',
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('cam_question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cam_question_id'], ['cam_question.camQuestionID'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quizID'], )
    )
    op.create_table('quiz_image_question',
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('image_question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_question_id'], ['image_question.imgQuestionID'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quizID'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_image_question')
    op.drop_table('quiz_camera_question')
    # ### end Alembic commands ###
