"""empty message

Revision ID: fdf15371d03b
Revises: 
Create Date: 2024-05-08 17:26:31.466874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf15371d03b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('administratorID', sa.Integer(), nullable=False),
    sa.Column('access_code', sa.String(length=10), nullable=True),
    sa.Column('fname', sa.String(length=50), nullable=True),
    sa.Column('lname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('administratorID'),
    sa.UniqueConstraint('access_code'),
    sa.UniqueConstraint('email')
    )
    op.create_table('participant',
    sa.Column('participantID', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=50), nullable=True),
    sa.Column('lname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('participantID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cam_question',
    sa.Column('camQuestionID', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=255), nullable=True),
    sa.Column('adminID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adminID'], ['administrator.administratorID'], ),
    sa.PrimaryKeyConstraint('camQuestionID')
    )
    op.create_table('enrol',
    sa.Column('enrolID', sa.Integer(), nullable=False),
    sa.Column('accessCode', sa.String(length=10), nullable=False),
    sa.Column('participantID', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accessCode'], ['administrator.access_code'], ),
    sa.ForeignKeyConstraint(['participantID'], ['participant.participantID'], ),
    sa.PrimaryKeyConstraint('enrolID')
    )
    op.create_table('image_question',
    sa.Column('imgQuestionID', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('adminID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adminID'], ['administrator.administratorID'], ),
    sa.PrimaryKeyConstraint('imgQuestionID')
    )
    op.create_table('leaderboard',
    sa.Column('lboardID', sa.Integer(), nullable=False),
    sa.Column('participantID', sa.Integer(), nullable=True),
    sa.Column('adminID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adminID'], ['administrator.administratorID'], ),
    sa.ForeignKeyConstraint(['participantID'], ['participant.participantID'], ),
    sa.PrimaryKeyConstraint('lboardID')
    )
    op.create_table('quiz',
    sa.Column('quizID', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('numQuestions', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('adminID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adminID'], ['administrator.administratorID'], ),
    sa.PrimaryKeyConstraint('quizID')
    )
    op.create_table('administered',
    sa.Column('participantID', sa.Integer(), nullable=False),
    sa.Column('quizID', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['participantID'], ['participant.participantID'], ),
    sa.ForeignKeyConstraint(['quizID'], ['quiz.quizID'], ),
    sa.PrimaryKeyConstraint('participantID', 'quizID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administered')
    op.drop_table('quiz')
    op.drop_table('leaderboard')
    op.drop_table('image_question')
    op.drop_table('enrol')
    op.drop_table('cam_question')
    op.drop_table('participant')
    op.drop_table('administrator')
    # ### end Alembic commands ###
